CFI/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('form.urls')),
]

form/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('project/', views.project, name='project'),
]

form/models.py
from django.db import models

# Create your models here.
class customer(models.Model):
    name = models.CharField(max_length= 200, null =True)
    phone = models.CharField(max_length=10, null =True)
    age = models.CharField(max_length=3, null =True)
    city = models.CharField(max_length= 200, null =True)

    def __str__(self):
        return self.name

form/forms.py
from importlib.metadata import files
from typing import OrderedDict
from django.forms import ModelForm
from .models import *

class CustomerForm(ModelForm):
    class Meta:
        model = customer
        fields = '__all__'

form/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *

# Create your views here.

def home(request):
    return render(request, 'form/index.html')

def project(request):
    
    users = customer.objects.all()
    form = CustomerForm()
    if request.method == 'POST':
        print(request.POST)
        form = CustomerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/project')
    

    username = request.GET.get('Name')
    check = bool(username)
    for i in list(users):
        if username == i.name or username == '':
            check = False
    filteredUsers = users.filter(name = username)
    if username == "_all_" or username == "_All_":
        filteredUsers = users
        check = False
    context = {'form': form, "users": filteredUsers, "check":check}
    return render(request, 'form/project.html', context)

form/templates/form/Index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CFI App</title>
    <link rel="stylesheet" href="{% static '/css/Style.css' %}" />
  </head>
  <body>
    <div class="landing-page">
      <div class="nav-bar">
        <ul class="nav-items">
          <li><a href="" id="logo">DK</a></li>
        </ul>
        <a href="https://github.com/DK-GitHub-DK" id="github" target="_blank"
          >GitHub</a
        >
      </div>
      <div class="image">
        <img src="{% static '/images/Portfolio2.png' %}" alt="" />
      </div>
      <div class="main-content">
        <p class="hello">
          <span class="line"> </span>
          Hello
        </p>
        <p class="name">I'm<span class="first-name">Dheeraj</span>Kumar</p>
        <p class="intro">
          An aspiring Full-Stack Developer and your new Project Member
        </p>
        <div class="CTA">
          <span class="button"
            ><a
              href="{% static '/images/CFI_APP.pdf' %}"
              target="_blank"
              >Application</a
            ></span
          >
          <span class="button"><a href={% url 'project' %}>Project</a></span>
        </div>
      </div>
    </div>
  </body>
</html>

form/templates/form/project.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static '/css/projectStyles.css' %}" />
    <title>Project</title>
  </head>
  <body>
    <div class="main-content">
      <div class="form">
        <form action="" method="POST">
          {% csrf_token %}
          <!-- <input
            type="hidden"
            name="csrfmiddlewaretoken"
            value="0w9xOrCsQ1gI92xh4mYFub4KL8GR7htPrJRcL704P0cfm3h1SvLiua2bl4zBS88s"
          /> -->
          <div class="form-element">
            <label for="id_name">Name:</label
            ><input
              type="text"
              name="name"
              maxlength="200"
              required=""
              id="id_name"
            />
          </div>
          <div class="form-element">
            <label for="id_phone">Phone:</label
            ><input
              type="text"
              name="phone"
              maxlength="10"
              required=""
              id="id_phone"
            />
          </div>
          <div class="form-element">
            <label for="id_age">Age:</label
            ><input
              type="text"
              name="age"
              maxlength="3"
              required=""
              id="id_age"
            />
          </div>
          <div class="form-element">
            <label for="id_city">City:</label
            ><input
              type="text"
              name="city"
              maxlength="200"
              required=""
              id="id_city"
            />
          </div>
          <input class="btn btn-sm btn-success" type="submit" name="Submit" />
        </form>
      </div>
      <div class="table-container">
        <div class="table-search">
          <form action="" method="GET">
            <div class="name">
              <label for="Name">Name:&nbsp;&nbsp;&nbsp;</label>
              <input type="text" name="Name" />
            </div>
            {% if check %}
            <div class="alert alert-danger" role="alert" id="error">
              Name doesn't exist
            </div>
            {% endif %}
            <input type="submit" value="Search" class="btn btn-sm btn-info" />
          </form>
        </div>

        <div class="col-md-6">
          <div class="card card-body">
            <table class="table table-sm">
              <tr>
                <th>Name</th>
                <th>Phone</th>
                <th>Age</th>
                <th>City</th>
              </tr>
              {% for i in users %}
              <tr>
                <td>{{i.name}}</td>
                <td>{{i.phone}}</td>
                <td>{{i.age}}</td>
                <td>{{i.city}}</td>
              </tr>
              {% endfor %}
            </table>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>